# Implement a multilayer perceptron - practice Assignments

In [4]:
import numpy as np
import sys

# Create a class - NeuralNetwork (for multilayer perceptron)

In [5]:
class NeuralNetwork():
    def __init__(self):
        # Seed the random number generator
        np.random.seed(2)
        # Initialize weights for the input layer (3 neurons) and hidden layer (4 neurons)
        self.input_weights = 2 * np.random.random((3, 4)) - 1
        self.hidden_weights = 2 * np.random.random((4, 1)) - 1

    # Create a sigmoid activation function
    def _sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def _sigmoid_derivative(self, x):
        return x * (1 - x)

    def think(self, inputs):
        # Calculate output for the hidden layer
        hidden_output = self._sigmoid(np.dot(inputs, self.input_weights))
        # Calculate final output for the network
        final_output = self._sigmoid(np.dot(hidden_output, self.hidden_weights))
        return final_output

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Forward propagation
            hidden_output = self._sigmoid(np.dot(training_set_inputs, self.input_weights))
            final_output = self._sigmoid(np.dot(hidden_output, self.hidden_weights))

            # Calculate the error
            error = training_set_outputs - final_output

            # Backpropagation and weight adjustments
            hidden_error = error.dot(self.hidden_weights.T) * self._sigmoid_derivative(hidden_output)
            self.hidden_weights += hidden_output.T.dot(error * self._sigmoid_derivative(final_output))
            self.input_weights += training_set_inputs.T.dot(hidden_error)



# Initialize the Network

In [6]:
if __name__ == "__main__":
    
    # Initialize the neural network
    neural_network = NeuralNetwork()
    
    # Print random starting weights
    print('Random starting weights:\n')
    print("Input Layer Weights:\n", neural_network.input_weights)
    print("Hidden Layer Weights:\n", neural_network.hidden_weights)

    # here we training data (3 input neurons, 1 output neuron)
    training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = np.array([[0], [1], [1], [0]])

Random starting weights:

Input Layer Weights:
 [[-0.1280102  -0.94814754  0.09932496 -0.12935521]
 [-0.1592644  -0.33933036 -0.59070273  0.23854193]
 [-0.40069065 -0.46634545  0.24226767  0.05828419]]
Hidden Layer Weights:
 [[-0.73084011]
 [ 0.02715624]
 [-0.63112027]
 [ 0.5706703 ]]


# Train the Neural Network

In [11]:
# Train the neural network for 10,000 iterations

print('********************* Neural Network Training Phase*********************')

number_of_training_iterations = 10000
neural_network.train(training_set_inputs, training_set_outputs, number_of_training_iterations)

# Print updated weights after training
print('\nNew weights after training:\n')
print("Input Layer Weights:\n", neural_network.input_weights)
print("Hidden Layer Weights:\n", neural_network.hidden_weights)

# Test the neural network with a new situation [1, 0, 0]
new_input = np.array([1, 0, 0])  # Changing the input values here
output = neural_network.think(new_input)
print("\nPredicted output after training: ", output)

********************* Neural Network Training Phase*********************

New weights after training:

Input Layer Weights:
 [[-11.63402986 -10.11016959 -11.29022418  13.07017167]
 [  0.3809136    0.39239396   0.37238557  -0.37453618]
 [  5.12780194   4.35528322   4.96037313  -5.85159699]]
Hidden Layer Weights:
 [[-2.83275132]
 [-1.48929507]
 [-2.43750544]
 [ 6.13786504]]

Predicted output after training:  [0.99784485]
